### PR TITLE
use bluepront to organise routes

### PR DESCRIPTION
**Pull request by shreeup**

### CODE REVIEW

**Comment by shreeup** [comment]
@bigolboyyo / @futuresoup  Could you please review changes? Or you think should i go ahead and merge

**Comment by bigolboyyo** [comment]
@shreeup | @futuresoup | @howard989 

This is a great start. I've been tinkering with this as well and have worked out some additional error handling. We can merge this and I'll make a pull later today/tomorrow adding the error handling and most likely a circular import/coroutine issue fix I am suspecting to run into haha

Thanks Shree, great work! 

I recommend checking out [asyncio](https://docs.python.org/3/library/asyncio.html) if you run into async issues.

Remember to properly utilize __init__.py files to prevent circular imports

And lastly if you want to get crazy with the power of Flask check out [Application Factories](https://flask.palletsprojects.com/en/0.12.x/patterns/appfactories/)

**Review by bigolboyyo — CHANGES_REQUESTED** [review]
Need testing evidence that Flask app runs, no coroutine issues, circular imports. And the http request gets handled correctly

**Comment by shreeup** [comment]
I am seeing an error in when i try to run flask run. Please find debug trace below
```

(venv) shree@rahuls-mac-mini app % flask run --debug
/Users/shree/Downloads/OpenSource/ClimateTech-data-magic/app/api
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app.app', an ImportError was raised:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/shree/Downloads/OpenSource/ClimateTech-data-magic/app/app.py", line 9, in <module>
    from utils.utils import get_env_vars, create_generator
ModuleNotFoundError: No module named 'utils'
```

I am trying to fix this issue.

**Comment by shreeup** [comment]
proof of testing

image

**Review by bigolboyyo — APPROVED** [review]
Great notice on the absolute path and module error! It looks like a 200 response on the tags. I'll keep working on the additional error handling I have in mind and have more documentation for that in the next day or two.

Great work

**Pull request merged**
